---
bind: 0.0.0.0:80             # address and port to bind on
allow-transfers: true        # allow log file downloads
follow-names: false          # allow tailing of not-yet-existent files
relative-root: ''            # web app root path (default: '')
commands: [tail, grep, awk]  # allowed commands
tail-lines: 100              # number of lines to tail initially
wrap-lines: false            # initial line-wrapping state

files:
  - '/logs/*.log'            # all files in this directory

http-auth: basic             # enable authentication (optional)
users:                       # password access (optional)
  myuser: mypassword
