version: '3'
services:
  demo_boot_service:
    image: openjdk:8-alpine
    container_name: demo-boot
    environment:
      JAVA_OPTS: ""
    command: java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /demo.jar
    ports:
      - "8080:8080"
    volumes:
      - "/home/docker/demo-0.0.1-SNAPSHOT.jar:/demo.jar:ro"
      - "/home/docker/application.properties:/application.properties:ro"
      - "/tmp:/tmp"
