version: '3'
services:
  influxdb_service:
    image: influxdb:1.2
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086" # HTTP API port
#      - "8083:8083" # Administrator interface port, if it is enabled (deprecated)
#      - "2003:2003" # Graphite support, if it is enabled
    volumes:
      - "/influxdb/data:/var/lib/influxdb"
      - "/influxdb/logs:/var/log/influxdb/"
